env:
    browser: true
    commonjs: true
    es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
    sourceType: module
globals:
    process: true
rules:
    indent:
        - error
        - 4
        -
            SwitchCase: 1
            VariableDeclarator: 1
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - always
    no-console:
        - off
    no-unused-vars:
        - error
        - varsIgnorePattern: "styles"
