port: 9898

secrets:
    cookie: 1RIIyW1F9LSP5z7OBeVM9K0S1h67b92I

files:
    dir: files
    tmpDir: tmp

qrcodes:
    dir: files/qrcodes

sendgrid:
    key: ""

email:
    templatesPath: emails
    logoUrl: https://dockas.com/assets/images/logo_400x88.png

    invitation:
        templateFileName: invitation.pug
        fromname: Dockas
        from: invitations-noreply@dockas.com
        subject: Seu convite Dockas chegou!
        signupUrl: https://dockas.com/signup

db:
    mongo:
        url: mongodb://mongo.service.consul:27017/Dockas
        testUrl: mongodb://mongo.service.consul:27017/DockasTest
    redis:
        url: redis://redis.service.consul:6379
        secret: 1RIIyW1F9LSP5z7OBeVM9K0S1h67b92I
        no_ready_check: true

auth:
    token:
        expiration: 604800

rootUser:
    fullName: Dockas Root
    email: root@dockas.com
    password: Mula*8
    deletedAt: null
    roles:
        - admin

activation:
    ticket:
        expiration: 216000