port: 9898

secrets:
    cookie: 1RIIyW1F9LSP5z7OBeVM9K0S1h67b92I

files:
    dir: files
    tmpDir: tmp

qrcodes:
    dir: files/qrcodes

sendgrid:
    key: ""

minOrderTotalPrice: 7000

hostnames:
    webapp: dockas.com
    api: api.dockas.com
    socket: socket.dockas.com
    file: file.dockas.com

email:
    lang: pt-br
    fromname: Dockas
    from: noreply@dockas.com

    urls:
        logo: https://dockas.com/assets/images/logo_400x88.png
        signup: https://dockas.com/signup
        images: https://file.dockas.com/images

sms:
    lang: pt-br

db:
    mongo:
        url: mongodb://mongo.service.consul:27017/Dockas
        testUrl: mongodb://mongo.service.consul:27017/DockasTest
    redis:
        url: redis://redis.service.consul:6379
        secret: 1RIIyW1F9LSP5z7OBeVM9K0S1h67b92I
        no_ready_check: true
    arango:
        url: tcp://root:@arango.service.consul:8529
        database: Dockas

billing:
    notifications:
      port: 9595

crypt:
    key: ""

auth:
    token:
        expiration: 604800

rootUser:
    fullName: Dockas Root
    email: root@dockas.com
    password: Mula*8
    maxBrandCount: 1
    brandCount: 0
    deletedAt: null
    postalCodeAddress:
        neighborhood: Santo Antônio
        street: Professor Arduino Bolivar
        city: Belo Horizonte
        state: MG
        country: BRA
        postalCode: 30350140
    roles:
        - admin

user:
    maxBrandCount: 1

brand:
    maxProductCount: 5

activation:
    ticket:
        expiration: 216000

currency:
    symbol: "R$"
    code: "BRL"

alerts:
    orderStatusUpdated:
        open__awaiting_user_availability:
            onOptionSelectedAction: alertOptionActionOrderUserAvailabilityUpdate
            options:
                - label: _YES_
                  value: yes
                - label: _NO_
                  value: no

notifications:
    orderStatusUpdated:
        ready__awaiting_user_availability:
            onOptionSelectedAction: notificationOptionActionOrderUserAvailabilityUpdate
            options:
                - label: _YES_
                  value: yes
                - label: _NO_
                  value: no

# Shared config keys
shared:
    - minOrderTotalPrice